# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  diff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr
        python -m pip install --upgrade pip
        pip install git+https://github.com/COVID19Tracking/urlwatch.git -r https://raw.githubusercontent.com/COVID19Tracking/urlwatch/master/requirements-dev.txt
    - name: Make output dirs
      run: |
        mkdir output_base output_pr

    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        path: pr

    - name: Checkout base
      uses: actions/checkout@v2
      with:
        path: base
        ref: ${{ github.event.pull_request.base.ref }}
    
    - name: Run PR
      run: |
        python3 pr/evaluator.py --output_dir=output_pr
    
    - name: Run base
      run: |
        python3 base/evaluator.py --output_dir=output_base
        
    - name: Diff
      run: |
        # diff returns an error code if there are changs
        diff -r output_base output_pr || true
      

    
