# This workflow deploys new code to our server after a commit happens

name: Deploy

# Triggers the workflow for push events on the master branch only
on: 
  push:
    branches:
      - deploy-workflow # TODO: change to 'master'

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        debug: true
        script: |
          cd covid-tracking-test
          git pull

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_COLOR: '#3278BD'
        SLACK_MESSAGE: 'The previous changes has been deployed'
        SLACK_TITLE: Commit Deployed
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

