# This workflow deploys new code to our server after a commit happens

name: Deploy

# Triggers the workflow for push events on the master branch only
on: 
  push:
    branches:
      - deploy-workflow # TODO: change to 'master'

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout pull request
      uses: actions/checkout@v2

    - name: Debug
      run: |
        echo "${{ secrets.SSH_HOST }}"
        echo "${{ secrets.SSH_USERNAME }}"
        echo "${{ secrets.SSH_KEY }}"

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase:
        debug: true
        script: |
          cd covid-tracking-test
          git pull

